# Generated by Django 4.2.25 on 2025-10-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='farmer',
            name='worker_type',
            field=models.CharField(choices=[('casual', 'Casual Worker (Wage)'), ('contract', 'Contract Worker')], default='casual', max_length=10),
        ),
    ]
